include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: true
    lines_longer_than_120_chars: true

    use_string_buffers: false
    no_logic_in_create_state: false
