include: package:lint/analysis_options.yaml

linter:
  rules:
    # NOTE: O arquivo tรก com mais de 300 linhas? 
    # hora de criar um Widget novo pra reduzir o tamanho dele
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: true
    lines_longer_than_100_chars: true
    sort_pub_dependencies: true