name: perna
description: A new Flutter project.

version: 2.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

# TODO: atualizar versões das dependencias para null safety
# flutter pub outdated --mode=null-safety
# flutter_google_places    ✗0.2.8   ✗0.2.8      ✗0.2.8      ✗0.2.8 (google_places_picker: ^3.0.0-nullsafety.0)
# stripe_payment           ✗1.0.10  ✗1.0.10     ✗1.0.10     ✗1.0.10 (api_service?)

dependencies:
  android_intent: ^2.0.0
  app_settings: ^4.1.0
  avatar_glow: ^2.0.0
  cloud_firestore: ^1.0.0
  connectivity: ^3.0.2
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  # NOTE: firebase_messaging ta com uma issue com in-app messages https://github.com/FirebaseExtended/flutterfire/issues/5331
  firebase_messaging: ^9.0.0  
  flutter:
    sdk: flutter
  # TODO: verificar se mergiou
  flutter_datetime_picker:
    git:
      url: https://github.com/figengungor/flutter_datetime_picker.git
      ref: null_safety_feature
  # TODO: verificar se mergiou
  flutter_flavor:
    git:
      url: https://github.com/safarmer/flutter_flavor.git
      ref: feature/null-safety
  flutter_geocoder: ^0.2.2-nullsafety
  flutter_google_places: ^0.2.8
  flutter_local_notifications: ^5.0.0-nullsafety.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^1.0.9
  flutter_rating_bar: ^4.0.0
  # TODO: verificar se mergiou
  flutter_redux:
    git:
      url: https://github.com/Lafannn/flutter_redux.git
      ref: null-safety
  # TODO: verificar se mergiou
  flutter_speed_dial:
    git:
      url: https://github.com/darioielardi/flutter_speed_dial.git
      ref: master
  flutter_spinkit: ^5.0.0
  geolocator: ^7.0.1
  get_it: ^6.0.0
  google_maps_flutter: ^2.0.1
  google_maps_webservice: ^0.0.20-nullsafety.0
  google_sign_in: ^5.0.0
  http: ^0.13.0
  http_parser: ^4.0.0
  location: ^4.1.1
  random_color: ^1.0.6-nullsafety
  # TODO: Em https://github.com/kevmeyer/redux_persist.git, verificar se mergiou
  redux_persist:
    git:
      url: https://github.com/kevmeyer/redux_persist.git
      path: packages/redux_persist
      ref: km_null_safety
  # TODO: Em https://github.com/kevmeyer/redux_persist.git, verificar se mergiou
  redux_persist_flutter:
    git:
      url: https://github.com/Aryelld/redux_persist.git
      path: packages/redux_persist_flutter
      ref: km_null_safety
  stripe_payment: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
  uses-material-design: true
  assets: 
    - icons/
    - assets/
    - lang/en.json
    - lang/pt.json
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
