name: perna
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.25
  google_map_polyline: ^0.2.0+1
  flutter_redux: ^0.6.0
  http: ^0.12.0+4
  google_sign_in: ^4.2.0
  avatar_glow: ^1.1.0
  numberpicker: ^1.2.0
  toast: ^0.1.5
  location: ^2.5.0
  redux_persist: ^0.8.3
  datetime_picker_formfield: ^1.0.0
  redux_persist_flutter: ^0.8.2
  flutter_bloc: ^2.1.1
  geolocator: ^5.3.1
  flutter_markdown: ^0.3.4
  connectivity: ^0.4.2
  loading: ^1.0.2
  app_settings: 3.0.1
  cloud_firestore: ^0.13.4+2
  firebase_core: ^0.4.4
  timeline_list: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        # - asset: fonts/ProductSans-Italic.ttf
        #   style: italic
        # - asset: fonts/ProductSans-Bold.ttf
        #   style: bold
