name: perna
description: A new Flutter project.

version: 2.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  stripe_payment: ^1.0.10
  flutter_speed_dial: ^2.1.1
  flutter_datetime_picker: ^1.5.0
  flutter_redux: ^0.7.0
  http: ^0.13.0
  google_sign_in: ^5.0.0
  avatar_glow: ^1.2.0
  location: ^4.0.2
  redux_persist: ^0.8.4
  datetime_picker_formfield: ^2.0.0
  geolocator: ^7.0.1
  geocoder: ^0.2.1
  random_color: ^1.0.5
  flutter_flavor: ^1.1.3
  connectivity: ^3.0.2
  loading: ^1.0.2
  app_settings: ^4.1.0
  cloud_firestore: ^1.0.0
  firebase_core: ^1.0.0
  firebase_messaging: ^9.0.0  
  android_intent: ^2.0.0
  flutter_rating_bar: ^4.0.0
  firebase_auth: ^1.0.0
  http_parser: ^4.0.0
  redux_persist_flutter: ^0.8.2
  flutter_local_notifications: ^5.0.0-nullsafety.0
  google_maps_webservice: ^0.0.20-nullsafety.0
  flutter_google_places: ^0.2.8
  google_maps_flutter: ^2.0.1
  flutter_native_timezone: ^1.0.9

dev_dependencies:
  lint: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - icons/
    - assets/
    - lang/en.json
    - lang/pt.json
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
